# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  SharedLibrary_config = debug
  Team_config = debug
  Broker_config = debug
  gameboy_config = debug
  GameCard_config = debug
endif
ifeq ($(config),release)
  SharedLibrary_config = release
  Team_config = release
  Broker_config = release
  gameboy_config = release
  GameCard_config = release
endif

PROJECTS := SharedLibrary Team Broker gameboy GameCard

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SharedLibrary:
ifneq (,$(SharedLibrary_config))
	@echo "==== Building SharedLibrary ($(SharedLibrary_config)) ===="
	@${MAKE} --no-print-directory -C SharedLibrary -f Makefile config=$(SharedLibrary_config)
endif

Team: SharedLibrary
ifneq (,$(Team_config))
	@echo "==== Building Team ($(Team_config)) ===="
	@${MAKE} --no-print-directory -C Team -f Makefile config=$(Team_config)
endif

Broker: SharedLibrary
ifneq (,$(Broker_config))
	@echo "==== Building Broker ($(Broker_config)) ===="
	@${MAKE} --no-print-directory -C Broker -f Makefile config=$(Broker_config)
endif

gameboy: SharedLibrary
ifneq (,$(gameboy_config))
	@echo "==== Building gameboy ($(gameboy_config)) ===="
	@${MAKE} --no-print-directory -C gameboy -f Makefile config=$(gameboy_config)
endif

GameCard: SharedLibrary
ifneq (,$(GameCard_config))
	@echo "==== Building GameCard ($(GameCard_config)) ===="
	@${MAKE} --no-print-directory -C GameCard -f Makefile config=$(GameCard_config)
endif

clean:
	@${MAKE} --no-print-directory -C SharedLibrary -f Makefile clean
	@${MAKE} --no-print-directory -C Team -f Makefile clean
	@${MAKE} --no-print-directory -C Broker -f Makefile clean
	@${MAKE} --no-print-directory -C gameboy -f Makefile clean
	@${MAKE} --no-print-directory -C GameCard -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SharedLibrary"
	@echo "   Team"
	@echo "   Broker"
	@echo "   gameboy"
	@echo "   GameCard"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"